variables:
    SERIES_BRANCH: '15.0'
    CI_JOB_TOKEN_GIT_HOST: 'gitlab.crnd.pro'

    PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.hidden-pip-cache"

# Disable global cache
cache: {}

.pip_cache: &pip_cache_definition
    cache:
        key: ${CI_JOB_NAME}
        paths:
            - "${PIP_CACHE_DIR}"

stages:
    - package
    - build
    - deploy

.do_package_definition: &do_package_definition
    image: registry.crnd.pro/crnd/docker/odoo-apps-packager:d
    stage: package
    before_script:
        - odoo-packager --info-only
        - odoo-packager --version
    script:
        - odoo-packager --dist .

do_package_on_commit:
    <<: *do_package_definition
    except:
        variables:
            # Do not run package on commits created by packager itself
            - $CI_COMMIT_MESSAGE =~ /\[odoo-packager\]/
            - $CI_COMMIT_MESSAGE =~ /\[yodoo-cockpit\]/
        refs:
            - "15.0"
            - web
            - api
    only:
        refs:
            - branches
        changes:
            - "odoo-packager.yml"

do_package_manual_or_api:
    <<: *do_package_definition
    except:
        - "15.0"
    only:
        - web
        - api




